description: My online Resume
datelastupdated: 25 Nov 2021
fullnameofperson: Estefania Arteaga Valdivia
selfIdentification: Environmental Consultant - Researcher
colour1: "#1E2F23"  # sidebar background 
colour2: "#FFFFFF"  # colour of name and desc
colour3: "#a3cef1"  # colour of Menu links
colour4: "#768948" # trying to be background colour
colour5: "#e7ecef" # menu link colour when hover
