description: My online Resume
datelastupdated: 25 Nov 2021
fullnameofperson: Estefania Arteaga Valdivia
selfIdentification: Environmental Consultant - Researcher
colour1: "#274c77"  # sidebar background 
colour2: "#a3cef1"  # colour of name and desc
colour3: "#a3cef1"  # colour of Menu links
colour4: "#d4dfc7" # trying to be background colour - still experimenting 
colour5: "#e7ecef" # menu link colour when hover
